import numpy as np
X = np.array([[1, 2,3 ],
[4, 5, 6],
[7, 8, 9]])
X_cube_multiply = np.multiply(X, np.multiply(X, X))
X_cube_operator = X * X * X
X_cube_power = np.power(X, 3)
X_cube_double_star = X ** 3
identity_matrix = np.identity(X.shape[0])
X_power_2 = np.power(X, 2)
X_power_3 = np.power(X, 3)
X_power_4 = np.power(X, 4)
print("ORIGINAL MATRIX X:")
print(X)
print("\nCUBED MATRIX (Method 1 - multiply()):")
print(X_cube_multiply)
print("\nCUBED MATRIX (Method 2 - * operator):")
print(X_cube_operator)
print("\nCUBED MATRIX (Method 3 - power()):")
print(X_cube_power)
print("\nCUBED MATRIX (Method 4 - ** operator):")
print(X_cube_double_star)
print("\nIDENTITY MATRIX:")
print(identity_matrix)
print("\nMATRIX TO DIFFERENT POWERS:")
print("X^2:")
print(X_power_2)
print("\nX^3:")
print(X_power_3)
print("\nX^4:")
print(X_power_4)